name: 'Setup Version'
description: 'Read version from a file and do something with it'

runs:
    using: "composite"

    steps:
      - name: Get Version
        shell: bash
        id: get-version
        run: echo "version=$(cat .versionrc)" >> "${GITHUB_OUTPUT}"

      - shell: bash
        if: ${{ steps.get-version.outputs.version == '' }}
        run: exit 1

      - name: Set Up (${{ steps.get-version.outputs.version }})
        shell: bash
        run: echo "Setting up version ${{ steps.get-version.outputs.version }} of whatever"
