on:
    push:
        branches: [ main ]

jobs:
    build-branch:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/run-setup/
        - run: echo "Install dependencies ..."
        - run: echo "Build the project ..."

