on:
    pull_request:
        branches: [ main ]
        types: [ closed ]

jobs:
    get-deployment-env:
        runs-on: ubuntu-latest
        outputs:
            deployment-env: ${{ steps.get-deployment-env.outputs.deploymentEnv }}

        steps:
            - id: get-deployment-env
              if: github.event.pull_request.merged == true
              run: echo "deploymentEnv=develop" >> "${GITHUB_OUTPUT}"

    run-deployment:
        needs: get-deployment-env
        if: needs.get-deployment-env.outputs.deployment-env != ''
        name: "Deploy"
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        environment:
            name: ${{ needs.get-deployment-env.outputs.deployment-env }}
        env:
            DEPLOYMENT_ENV: ${{ needs.get-deployment-env.outputs.deployment-env }}
            ENV_SECRET_FOO: ${{ secrets.ENV_SECRET_FOO }}
            ENV_VAR_FOO: ${{ env.ENV_VAR_FOO }}
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/run-setup
            - uses: ./.github/actions/run-tests/
            - run: echo "Deployment Environment - ${DEPLOYMENT_ENV}"
            - name: Debug - Printing out env.
              run: env
            - run: echo "Foo = ${ENV_VAR_FOO}"
            - run: ./scripts/print_secret.sh
            - run: echo "[PR#${{ github.event.pull_request.number }}]${{ github.event.pull_request.title }}"
