on:
    # trigger the workflow on any pull request against the default branch (main)
    pull_request:
        types: [opened, reopened, synchronize]
        branches: [ main ]
    push:

#mod
jobs:
    run-tests:
        name: "Run the tests!"
        runs-on: ubuntu-latest

        defaults:
            run:
                shell: bash

        # if: ${{ github.event.pull_request.merged == true || (github.event.issue.pull_request && contains(github.event.issue.body, '@workflow run')) }}
        if: ${{ github.event.pull_request.merged == true || (github.event.push && contains(github.event.head_commit.message , '[FORCE buildAndPush]')) }}

        steps:
            -   name: get event info
                run: echo "${{ github }}" 
                    
            -   if: ${{ github.event.pull_request }}
                name: checkout (PR)
                uses: actions/checkout@v4

            -   if: ${{ github.event.push }}
                name: checkout (push @ ${{github.sha}})
                uses: actions/checkout@v4

            -   name: output github context
                run: echo "${{ github }}"
            - uses: ./.github/actions/run-setup/
            - uses: ./.github/actions/run-tests/
