on:
    # trigger the workflow on any pull request against the default branch (main)
    pull_request:
        types: [opened, reopened, synchronize]
        branches: [ main ]

jobs:
    enforceEditorConfig:
      permissions:
        contents: write
        pull-requests: write
        actions: write
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
      outputs:
        committed-fixes: ${{ steps.commit-changes.outputs.committed-fixes }}
      env:
        CI_COMMIT_MESSAGE: "[editorConfig] enforce .editorConfig"
        CI_COMMIT_AUTHOR: "${{ github.event.repository.name }} Continuous Integration"
      steps:
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.pull_request.head.ref }}

        # check to see if running against a commit created by this job.
        - id: is-auto-commit
          if: ${{ github.action.commits[0].message == env.CI_COMMIT_MESSAGE && github.action.commits[0].author.name == env.CI_COMMIT_AUTHOR }}
          run: echo "is-auto-commit=true" >> "${GITHUB_OUTPUT}"
        - name: print info
          run: |
            echo "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}@${GITHUB_HEAD_REF}"
        # check to see if the code adheres to the .editorConfig file
        - id: eclint-enforce
          # skip the rest of this job if running against a commit resulting from this job.
          if: ${{ steps.is-auto-commit.outputs.is-auto-commit != 'true' }}
          name: apply .editorconfig
          run: |
            # disable "exit immediately on error"
            set +e
            # check to see if changes are required - redirect stderr > stdout
            # (build steps will fail on output to stderr)
            npm exec -y eclint -- check 2>&1

            # apply fixes if eclint found any issues
            if [[ ! $? -eq 0 ]]; then
              npm exec -y eclint -- fix
              # restore .github/ directory from index (github permissions issue)
              git checkout .github/
              echo "applied-fixes=true" >> "${GITHUB_OUTPUT}"
            fi
        # commit any changes made in eclint-enforce
        - id: commit-changes
          name: commit changes
          if: ${{ steps.eclint-enforce.outputs.applied-fixes == 'true' }}
          run: |
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR}}"
            git config --global user.email "ch4ni@adahome.dev"
            git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push --verbose
            echo "committed-fixes=true" >> "${GITHUB_OUTPUT}"

    run-tests:
        name: "Run the tests!"
        runs-on: ubuntu-latest

        needs: enforceEditorConfig

        # skip running tests if there's a new commit queued against the PR.
        if: ${{ needs.enforceEditorConfig.outputs.committed-fixes != 'true' }}

        steps:
            - uses: actions/checkout@v4
              with:
                ref: ${{ github.event.pull_request.head.ref }}
            - name: Show Commit Info
              run: |
                echo "Showing info from the last 10 commits:"
                git log --pretty=format:"%C(yellow)%h %ar %C(auto)%d %Creset %s, %Cblue%cn" --graph
            - uses: ./.github/actions/run-setup/
            - uses: ./.github/actions/run-tests/
